version: "2.3"
services:
  nodeserver:
    image: ${IMAGE:-geotrek-rando-v3/geotrek-rando}
    restart: always
    ports:
      - "${PORT:-8080}:3000"
    volumes:
      - ./customization:/app/customization
      - ./media:/app/src/public/medias/
