version: "2.3"
services:
  nodeserver:
    image: "geotrek-rando:latest"
    restart: always
    ports:
      - "80:3000"
    security_opt:
      - seccomp:unconfined
    device_cgroup_rules:
      - 'c *:* rmw'
    volumes:
      - ./customization:/app/customization
      - ./media:/app/src/public/medias/
      - /dev:/dev
